FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY profiles_service.py .
CMD ["uvicorn", "profiles_service:app", "--host", "0.0.0.0", "--port", "8265", "--reload"]