up:
	docker-compose down --remove-orphans
	docker-compose up -d
	@echo "Profiles: http://localhost:8265/docs"
	@echo "Other: http://localhost:8161/docs"

down:
	docker-compose down

restart:
	docker-compose restart