events {}

http {
    server {
        listen 8080;
        
        location /api/profiles/ {
            proxy_pass http://profiles-svc-s17:8265/api/profiles/;
        }
        
        location /api/other/ {
            proxy_pass http://other-service:8001/api/other/;
        }
    }
}