# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\torders.v1\"2\n\x12\x43reateOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"\'\n\x16SubscribeOrdersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"%\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x32\x99\x01\n\rOrdersService\x12>\n\x0b\x43reateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x10.orders.v1.Order\x12H\n\x0fSubscribeOrders\x12!.orders.v1.SubscribeOrdersRequest\x1a\x10.orders.v1.Order0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=28
  _globals['_CREATEORDERREQUEST']._serialized_end=78
  _globals['_SUBSCRIBEORDERSREQUEST']._serialized_start=80
  _globals['_SUBSCRIBEORDERSREQUEST']._serialized_end=119
  _globals['_ORDER']._serialized_start=121
  _globals['_ORDER']._serialized_end=158
  _globals['_ORDERSSERVICE']._serialized_start=161
  _globals['_ORDERSSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
