replicaCount: 2

image:
  repository: primer/obraz
  tag: "stage"

service:
  name: profiles-svc-s17
  port: 8265

resources:
  requests:
    memory: "96Mi"
    cpu: "250m"
  limits:
    memory: "192Mi"
    cpu: "500m"