replicaCount: 1

image:
  repository: primer/obraz
  tag: "latest"

service:
  name: profiles-svc-s17
  port: 8265

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"