replicaCount: 3

image:
  repository: primer/obraz
  tag: "prod"

service:
  name: profiles-svc-s17
  port: 8265

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1000m"